packaging_format = 2

id = "hubzilla"
name = "Hubzilla"
description.en = "Decentralized publication platform and social network"
description.fr = "Plateforme de publication décentralisée et un réseau social"

version = "9.0~ynh1"

maintainers = [""]

[upstream]
license = "MIT"
website = "https://hubzilla.org"
code = "https://framagit.org/hubzilla/core"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://framagit.org/hubzilla/core/-/archive/9.0/core-9.0.tar.bz2"
        sha256 = "a55d86228ddc5d6801eb32ee2c1f689077836743c12a72e3f1a85ee2af20d2fd"
        autoupdate.strategy = "latest_gitlab_release"

        [resources.sources.addons]
        url = "https://framagit.org/hubzilla/addons/-/archive/9.0/addons-9.0.tar.bz2"
        sha256 = "c3abe3781e7dacf966075ed0ab227a9882df80dea0c80ee37d8ee374e5bc2105"
        autoupdate.strategy = "latest_gitlab_tag"
        autoupdate.upstream = "https://framagit.org/hubzilla/addons"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.2-curl, php8.2-gd, php8.2-pgsql, php8.2-mbstring, php8.2-xml, php8.2-zip, php8.2-cli, php8.2-imagick, php8.2-gmp"

    [resources.database]
    type = "postgresql"
