packaging_format = 2

id = "hubzilla"
name = "Hubzilla"
description.en = "Decentralized publication platform and social network"
description.fr = "Plateforme de publication décentralisée et un réseau social"

version = "10.0.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://hubzilla.org"
code = "https://framagit.org/hubzilla/core"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://framagit.org/hubzilla/core/-/archive/10.0.2/core-10.0.2.tar.bz2"
        sha256 = "b9be3537b652bb41aff87b958ca7ddce9b9aacffc1164704fd9623b8ecefbf23"
        autoupdate.strategy = "latest_gitlab_release"

        [resources.sources.addons]
        url = "https://framagit.org/hubzilla/addons/-/archive/10.0.2/addons-10.0.2.tar.bz2"
        sha256 = "410fc91bf8e933c6b2a85393349bf363bc2d995f1400c872edaf52c1a8a8e235"
        autoupdate.strategy = "latest_gitlab_tag"
        autoupdate.upstream = "https://framagit.org/hubzilla/addons"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.3-curl, php8.3-gd, php8.3-pgsql, php8.3-mbstring, php8.3-xml, php8.3-zip, php8.3-cli, php8.3-imagick, php8.3-gmp, php8.3-intl"

    [resources.database]
    type = "postgresql"
