packaging_format = 2

id = "hubzilla"
name = "Hubzilla"
description.en = "Decentralized publication platform and social network."
description.fr = "Plateforme de publication décentralisée et un réseau social."

version = "8.4.1~ynh1"

maintainers = ["Anmol Sharma"]

[upstream]
license = "MIT"
website = "https://zotlabs.org/page/hubzilla/hubzilla-project"
code = "https://framagit.org/hubzilla/core"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://framagit.org/hubzilla/core/-/archive/8.4.1/core-8.4.1.tar.gz"
        sha256 = "93dd8fc4d30da8a79a77303381b1451f8215c62f8b913e215664a9396cf47d61"
        autoupdate.strategy = "latest_github_tag"

        [resources.sources.app_addons]
        url = "https://framagit.org/hubzilla/addons/-/archive/8.4.1/addons-8.4.1.tar.gz"
        sha256 = "67f7b881f195b258c3d61922a6ce0f92832b907cafd5feb11b8abea4b2b055a0"
        autoupdate.strategy = "latest_github_tag"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.2-curl php8.2-gd php8.2-mysql php8.2-mbstring php8.2-xml php8.2-zip php8.2-cli php8.2-imagick"

    [resources.database]
    type = "mysql"
