packaging_format = 2

id = "hubzilla"
name = "Hubzilla"
description.en = "Decentralized publication platform and social network"
description.fr = "Plateforme de publication décentralisée et un réseau social"

version = "10.4.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://hubzilla.org"
code = "https://framagit.org/hubzilla/core"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://framagit.org/hubzilla/core/-/archive/10.4.2/core-10.4.2.tar.bz2"
        sha256 = "761960f7fffd7a1871c1dfc45afc89ed63f50b522cead93d54900ec8a468259d"
        autoupdate.strategy = "latest_gitlab_release"

        [resources.sources.addons]
        url = "https://framagit.org/hubzilla/addons/-/archive/10.4.2/addons-10.4.2.tar.bz2"
        sha256 = "5da4f4932fb121cbf4d088e15a2ed4e0bb61c5fb1a1bcdd6aefc0da7019dcb62"
        autoupdate.strategy = "latest_gitlab_tag"
        autoupdate.upstream = "https://framagit.org/hubzilla/addons"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.3-curl, php8.3-gd, php8.3-pgsql, php8.3-mbstring, php8.3-xml, php8.3-zip, php8.3-cli, php8.3-imagick, php8.3-gmp, php8.3-intl"

    [resources.database]
    type = "postgresql"
