test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3e89436957f5a6f9b426836d671ffbb133d7db62.name = "Upgrade from 8.6.3~ynh1"

