test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.database="mysql"

[some_additional_testsuite]

    only = ["install.subdir"]

    args.database="mpostgresql"