#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/etc/cron.d/$app"

#=================================================
# BACKUP THE DATABASE
#=================================================

if mysqlshow | grep -q "^| $db_name "; then
	# Backup MySQL database
	ynh_print_info "Backup of the MySQL database..."
	ynh_mysql_dump_db > mydb.sql
else
	# Backup PostgreSQL database
	ynh_print_info "Backup of the PostgreSQL database..."
	ynh_psql_dump_db > db.sql
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
