#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE THE DATABASE
#=================================================

if mysqlshow | grep -q "^| $db_name "; then
	ynh_script_progression "Removing  MySQL database..."
    mysql_remove
fi

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_config_remove_logrotate

ynh_config_remove_fail2ban

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
