#!/bin/bash

source .fonctions       # Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

domain=$(ynh_app_setting_get $app domain)
db_user=$(ynh_app_setting_get $app db_user)

REMOVE_BDD $db_user # Suppression de la base de donnée et de l'utilisateur associé.

SECURE_REMOVE '/var/www/$app'   # Suppression du dossier de l'application

REMOVE_NGINX_CONF       # Suppression de la configuration nginx

REMOVE_FPM_CONF # Suppression de la configuration du pool php-fpm

# Remove poller cron job
sudo rm -f /etc/cron.d/poller-cron


# Reload services after cleaning
sudo service php5-fpm reload
sudo service nginx reload

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m" # Restore normal color
